---
version: "3"
services:
  # Postgres DB exposed on port 5432    
  metaquery-db:
    container_name: metaquery-db
    image: library/postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    restart: always  
  # Metaquery server exposed on port 8080
  metaquery:
    container_name: metaquery
    image: pcorbel/metaquery:v0.1.0
    ports:
      - "8080:8080"
    environment:
      - CONFIG_FILE=/app/configs/config.yaml
    links:
      - "metaquery-db:metaquery-db"
    volumes:
      - "~/.config/gcloud/application_default_credentials.json:/tmp/application_default_credentials.json"
      - "../configs/config.yaml:/app/configs/config.yaml"
    restart: always  
