---
# BigQuery related configs
project: happn-analytics
labels:
  - metaquery
max_client_concurrency: 3

# DB related configs
db_hostname: metaquery-db
db_port: 5432
db_reset: false

# Project related configs
log_level: info
server_port: 8080
web_directory: /app/web/dist
cron_refresh: "0 0 8 * * *" # Documentation available here https://godoc.org/github.com/robfig/cron